export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART"
export const DELETE_CART = "DELETE_CART"
export const ADD_ORDER = "ADD_ORDER"

export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const INIT_PRODUCTS = "INIT_PRODUCTS"

export const IS_LOGGED_IN = "IS_LOGGED_IN"
export const IS_LOGGED_OUT = "IS_LOGGED_OUT"

export const NEW_AUTH_ERROR = "NEW_AUTH_ERROR"
export const INIT_ORDERS = "INIT_ORDERS"